# Generated by Django 4.0.5 on 2022-07-01 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 21, 35, 9, 332545)),
        ),
    ]
