# Generated by Django 4.0.5 on 2022-07-01 21:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_alter_cart_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='catalog_inclusion_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 21, 40, 48, 151960)),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='catalog_inclusion_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
