# Generated by Django 4.0.5 on 2022-07-01 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_alter_cap_catalog_inclusion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
